algoritmo "funções aritmeticas"
var
    a: inteiro
    b: real
    c: real
    d: real
    g: real
    h: real
    i: real
    j: real
    k: real
inicio
    a <- abs(-50)
    b <- exp(-50)
    c <- int(-50)
    d <- raizq(-50)
    j <- pi(-50)
    k <- sen(-50)
    g <- cos(-50)
    h <- tan(-50)
    i <- grauprad(-50)
    escreval(a)
    escreval(b)
    escreval(c)
    escreval(d)
    escreval(j)
    escreval(k)
    escreval(g)
    escreval(h)
    escreval(i)
fimalgoritmo