algoritmo "Nome do Programa"
var
    nasc: inteiro
    ano: inteiro
    res: inteiro
inicio
    escreval("em que ano estamos? ")
    leia(ano)
    escreval("em qua no você nascel? ")
    leia(nasc)
    res <- (ano - nasc)   
    escreval("então você tem provavelmente: ", res, " anos, acertei?")
    // ainda não sei dar uma resposta bolleana.
    escreva("Agradeço a execução do teste!")

fimalgoritmo