algoritmo "helpdivisão"
var
    contador, salto, valor: real
inicio
    contador <- 0
    escreva("Qual o numero de vezes do 0 até o valor? :")
    leia(valor)
    escreva("Qual o numero que quer multiplicar até o resultado? :")
    leia(salto)
    enquanto (contador <= valor) faca
        escreval(contador)
        contador <- contador + salto
    fimenquanto
    //sugesttão de codigo
    escreva("o numero ", salto ,", se repete *tantas* vezes até o valor ", valor,"!")
fimalgoritmo
